import type { LucideIcon, LucideProps } from 'lucide-react';
import {
  Accessibility,
  Album,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  ArrowLeft,
  Ban,
  BatteryCharging,
  BatteryFull,
  Bell,
  BellOff,
  Bluetooth,
  BookOpen,
  Bookmark,
  Box,
  BrushCleaning,
  Calculator,
  CalendarDays,
  Camera,
  ChartColumn,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleDot,
  CircleX,
  ClipboardList,
  ClipboardPaste,
  Clock3,
  Copy,
  Download,
  Eraser,
  FileText,
  Film,
  Folder,
  FolderOpen,
  FolderPlus,
  Gamepad2,
  Globe,
  HardDrive,
  Heart,
  History,
  House,
  Image,
  Images,
  Inbox,
  Info,
  Keyboard,
  Laptop,
  LayoutGrid,
  LifeBuoy,
  List,
  ListOrdered,
  Lock,
  Mail,
  MessageCircleQuestion,
  Minus,
  Monitor,
  MoonStar,
  MoreHorizontal,
  Music4,
  Network,
  PaintBucket,
  Paintbrush2,
  Pause,
  PencilLine,
  Plane,
  Play,
  PlayCircle,
  Plus,
  Power,
  Printer,
  Redo2,
  RefreshCw,
  Repeat,
  Repeat1,
  Reply,
  Save,
  Scissors,
  Search,
  SendHorizontal,
  Settings2,
  Shapes,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Shuffle,
  SkipBack,
  SkipForward,
  Skull,
  Smartphone,
  Sparkles,
  Square,
  SquareDashedMousePointer,
  Star,
  Sticker,
  StickyNote,
  Store,
  Strikethrough,
  SunMedium,
  Terminal,
  Trash2,
  Triangle,
  TriangleAlert,
  Type,
  Undo2,
  UserRound,
  Users,
  Video,
  Volume1,
  Volume2,
  VolumeX,
  Wifi,
  X,
  ZoomIn,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  accessibility: Accessibility,
  add: Plus,
  album: Album,
  align_center: AlignCenter,
  align_justify: AlignJustify,
  align_left: AlignLeft,
  align_right: AlignRight,
  airplane: Plane,
  alert: Bell,
  alert_off: BellOff,
  apps_list: LayoutGrid,
  arrow_clockwise: RefreshCw,
  arrow_download: Download,
  arrow_left: ChevronLeft,
  arrow_right: ChevronRight,
  arrow_up: ChevronUp,
  audio: Volume2,
  back: ChevronLeft,
  back_arrow: ArrowLeft,
  battery_10: BatteryFull,
  battery_saver: BatteryCharging,
  bluetooth: Bluetooth,
  bookmark: Bookmark,
  book: BookOpen,
  brush: Paintbrush2,
  brush_cleaning: BrushCleaning,
  calculator: Calculator,
  calendar_ltr: CalendarDays,
  camera: Camera,
  capture: CircleDot,
  chart: ChartColumn,
  chat_help: MessageCircleQuestion,
  check: Check,
  check_circle: CheckCircle2,
  clock: Clock3,
  clipboard_paste: ClipboardPaste,
  close: X,
  close_circle: CircleX,
  cone: Triangle,
  copy: Copy,
  critical: Skull,
  cube: Box,
  cut: Scissors,
  delete: Trash2,
  desktop_computer: Monitor,
  desktop_pc: Monitor,
  document: FileText,
  document_bullet_list: ClipboardList,
  double_check: CheckCheck,
  download: Download,
  eraser: Eraser,
  error: CircleX,
  folder: Folder,
  folder_add: FolderPlus,
  folder_open: FolderOpen,
  globe: Globe,
  hard_drive: HardDrive,
  heart: Heart,
  history: History,
  home: House,
  image: Image,
  image_multiple: Images,
  info: Info,
  keyboard: Keyboard,
  laptop: Laptop,
  layout_grid: LayoutGrid,
  list: List,
  list_ordered: ListOrdered,
  lock: Lock,
  magnifier: ZoomIn,
  mail: Mail,
  mail_arrow_up: SendHorizontal,
  mail_inbox: Inbox,
  minus: Minus,
  more_horizontal: MoreHorizontal,
  music_note_1: Music4,
  network_check: Network,
  note: StickyNote,
  notepad: FileText,
  pause: Pause,
  paint_bucket: PaintBucket,
  person: UserRound,
  person_support: LifeBuoy,
  phone: Smartphone,
  phone_laptop: Smartphone,
  play: Play,
  play_circle: PlayCircle,
  plus: Plus,
  power: Power,
  printer: Printer,
  prompt: Terminal,
  prohibited: Ban,
  redo: Redo2,
  refresh: RefreshCw,
  repeat: Repeat,
  repeat_1: Repeat1,
  rename: PencilLine,
  reply: Reply,
  save: Save,
  screenshot: Scissors,
  search: Search,
  settings: Settings2,
  settings_cog: Settings2,
  shapes: Shapes,
  shield_checkmark: ShieldCheck,
  shield_lock: Shield,
  shopping_cart: ShoppingCart,
  shuffle: Shuffle,
  sleep: MoonStar,
  social: Users,
  speaker_1: Volume1,
  speaker_2: Volume2,
  speaker_off: VolumeX,
  sparkles: Sparkles,
  sphere: Circle,
  square_dashed_mouse_pointer: SquareDashedMousePointer,
  star: Star,
  step_back: SkipBack,
  step_forward: SkipForward,
  sticker: Sticker,
  store_microsoft: Store,
  strikethrough: Strikethrough,
  sun: SunMedium,
  sync: RefreshCw,
  task_list_square_ltr: ClipboardList,
  terminal: Terminal,
  text_font: Type,
  triangle: Triangle,
  undo: Undo2,
  users: Users,
  video: Video,
  video_clip: Film,
  warning: TriangleAlert,
  wifi_1: Wifi,
  x: X,
  xbox_controller: Gamepad2,
  zoom_in: ZoomIn,
};

export function resolveSystemIcon(name: string): LucideIcon {
  const normalized = name.toLowerCase().replace(/-/g, '_');
  return ICONS[normalized] || FileText;
}

export function SystemIcon({ name, ...props }: { name: string } & LucideProps) {
  const Icon = resolveSystemIcon(name);
  return <Icon {...props} />;
}
